import {
  Javascript,
  Typescript,
  Python,
  ReactJs,
  Nextdotjs,
  Angular,
  Mongodb,
  Supabase,
  Postgresql,
  Mui,
  Styledcomponents,
  Redux,
  Apollographql,
  Graphql,
  Amazonaws,
  Nodedotjs,
  Flask,
} from '@icons-pack/react-simple-icons';

const SkillsData = [
  {
    id: 1,
    Icon: <Javascript color='rgb(247, 223, 30)' />,
    label: 'Javascript',
    siteUrl: `https://javascript.info`,
    type: 'language',
  },
  {
    id: 2,
    Icon: <Typescript color='rgb(0, 122, 204)' />,
    label: 'Typescript',
    siteUrl: `https://www.typescriptlang.org`,
    type: 'language',
  },
  {
    id: 3,
    Icon: <Python color='rgb(55, 118, 171)' />,
    label: 'Python',
    siteUrl: `https://www.python.org`,
    type: 'language',
  },
  {
    id: 4,
    Icon: <ReactJs color='rgb(55, 118, 171)' />,
    label: 'React',
    siteUrl: `https://reactjs.org`,
    type: 'frontend-framework',
  },
  {
    id: 5,
    Icon: <Nextdotjs color='rgb(255, 255, 255)' className='changeFill' />,
    label: 'Next.js',
    siteUrl: `https://nextjs.org`,
    type: 'frontend-framework',
  },
  {
    id: 6,
    Icon: <Angular color='rgb(221, 0, 49)' />,
    label: 'Angular',
    siteUrl: `https://angular.io`,
    type: 'frontend-framework',
  },
  {
    id: 7,
    Icon: <Nodedotjs color='rgb(51, 153, 51)' />,
    label: 'Node.js',
    siteUrl: `https://nodejs.org/en/`,
    type: 'server-side',
  },
  {
    id: 8,
    Icon: <Flask color='rgb(255, 255, 255)' className='changeFill' />,
    label: 'Flask',
    siteUrl: `https://flask.palletsprojects.com`,
    type: 'server-side',
  },
  {
    id: 9,
    Icon: <Mongodb color='rgb(71, 162, 72)' />,
    label: 'MongoDB',
    siteUrl: `https://www.mongodb.com`,
    type: 'database',
  },
  {
    id: 10,
    Icon: <Supabase color='rgb(52, 178, 123)' />,
    label: 'Supabase',
    siteUrl: `https://supabase.com`,
    type: 'database',
  },
  {
    id: 11,
    Icon: <Postgresql color='rgb(0, 100, 165)' />,
    label: 'PostreSQL',
    siteUrl: `https://www.postgresql.org`,
    type: 'database',
  },
  {
    id: 12,
    Icon: <Amazonaws color='rgb(255, 153, 0)' />,
    label: 'AWS',
    siteUrl: `https://aws.amazon.com`,
    type: 'cloud',
  },
  {
    id: 13,
    Icon: <Redux color='rgb(118, 74, 188)' />,
    label: 'Redux',
    siteUrl: `https://redux.js.org`,
    type: 'tools',
  },
  {
    id: 14,
    Icon: <Apollographql color='rgb(255, 255, 255)' className='changeFill' />,
    label: 'Apollo GraphQL',
    siteUrl: `https://www.apollographql.com`,
    type: 'tools',
  },
  {
    id: 15,
    Icon: <Graphql color='rgb(229, 53, 171)' />,
    label: 'GraphQL',
    siteUrl: `https://graphql.org/`,
    type: 'tools',
  },
  {
    id: 16,
    Icon: <Mui color='rgb(102, 178, 255)' />,
    label: 'MUI',
    siteUrl: `https://mui.com/`,
    type: 'tools',
  },
  {
    id: 17,
    Icon: <Styledcomponents color='rgb(235, 94, 119)' />,
    label: 'Styled-Components',
    siteUrl: `https://styled-components.com`,
    type: 'tools',
  },
];

export default SkillsData;
