import {
  ReactJs,
  Nextdotjs,
  Angular,
  Tailwindcss,
  Mongodb,
  Supabase,
  Postgresql,
  Mui,
  Styledcomponents,
  Redux,
  Apollographql,
  Graphql,
  Amazonaws,
  Nodedotjs,
  Flask,
} from '@icons-pack/react-simple-icons';

const SkillsData = [
  {
    id: 1,
    color: 'rgb(97, 218, 251)',
    Icon: <ReactJs color='rgb(97, 218, 251)' />,
    label: 'React',
    desc: 'A JavaScript library for building user interfaces',
    link: 'https://reactjs.org/',
  },
  {
    id: 2,
    color: 'rgb(255, 255, 255)',
    Icon: <Nextdotjs color='rgb(255, 255, 255)' />,
    label: 'Next.js',
    desc: 'The Intuitive Web Framework for building modern apps & websites with React.js',
    link: 'https://nextjs.org/',
  },
  {
    id: 3,
    color: 'rgb(118, 74, 188)',
    Icon: <Redux color='rgb(118, 74, 188)' />,
    label: 'Redux',
    desc: 'JavaScript library for managing and centralizing application state',
    link: 'https://redux.js.org/',
  },
  {
    id: 4,
    color: 'rgb(51, 153, 51)',
    Icon: <Nodedotjs color='rgb(51, 153, 51)' />,
    label: 'Node.js',
    desc: "A JavaScript runtime built on Chrome's V8 JavaScript engine",
    link: 'https://nodejs.org/en/',
  },
  {
    id: 5,
    color: 'rgb(221, 0, 49)',
    Icon: <Angular color='rgb(221, 0, 49)' />,
    label: 'Angular',
    desc: 'A component-based framework for building scalable web applications',
    link: 'https://angular.io/',
  },
  {
    id: 6,
    color: 'rgb(255, 255, 255)',
    Icon: <Flask color='rgb(255, 255, 255)' />,
    label: 'Flask',
    desc: 'A micro web framework written in Python.',
    link: 'https://flask.palletsprojects.com/en/2.2.x/',
  },
  {
    id: 7,
    color: 'rgb(229, 53, 171)',
    Icon: <Graphql color='rgb(229, 53, 171)' />,
    label: 'GraphQL',
    desc: 'Data query and manipulation language for APIs',
    link: 'https://graphql.org/',
  },
  {
    id: 8,
    color: 'rgb(56, 178, 172)',
    Icon: <Tailwindcss color='rgb(56, 178, 172)' />,
    label: 'Tailwind',
    desc: 'A utility-first CSS framework for rapidly building custom designs',
    link: 'https://tailwindcss.com/',
  },
  {
    id: 9,
    color: 'rgb(0, 128, 255)',
    Icon: <Mui color='rgb(0, 128, 255)' />,
    label: 'MUI',
    desc: 'Provides a simple, customizable, and accessible library of React components',
    link: 'https://mui.com/',
  },
  {
    id: 10,
    color: 'rgb(230 73 124)',
    Icon: <Styledcomponents color='rgb(230 73 124)' />,
    label: 'Styled-Components',
    desc: 'Library for using component-level styles in React applications',
    link: 'https://styled-components.com/',
  },
];

export default SkillsData;
